services:
  server:
    build: ./
    ports:
      - 80:80
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
